import { GitHubLogoIcon, EnvelopeClosedIcon } from "@radix-ui/react-icons";
import { type NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Øystensen.dev Personal Website</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-screen">
        <div className="h-full flex flex-col items-center justify-center">
          <Heading />
        </div>
        <div className="left-0 flex flex-wrap gap-2 p-4 items-center">
          <div className="text-center text-xl font-Inter text-neutral-500 inline-flex gap-2 items-center">Contact: 
            <a href="mailto:patrick.oytsensen@gmail.com" className="hover:text-cyan-300"><EnvelopeClosedIcon className="h-6 w-auto" /></a>
            <a href="https://github.com/PatrickSolberg" className="hover:text-cyan-300"><GitHubLogoIcon className="h-6 w-auto"/> </a>
          </div>
        </div>
      </main>
    </>
  );
};

const onMouseOver = (event: React.MouseEvent<HTMLHeadingElement>) => {
  const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZØÆÅ";
  let iteration = 0;

  let interval: NodeJS.Timeout | undefined = undefined;

  clearInterval(interval);

  interval = setInterval(() => {
    const target = event.target as HTMLHeadingElement;
    target.textContent = target.textContent
      ?.split("")
      .map((letter, index) => {
        if (index < iteration) {
          return target.dataset.value?.[index];
        }

        return letters[Math.floor(Math.random() * 29)];
      })
      .join("");

    if (iteration >= target.dataset.value?.length) {
      clearInterval(interval);
    }

    iteration += 1 / 3;
  }, 30);
};

const Heading: React.FC = () => {
  const name = "Øystensen.dev";
  const msg = "Coming soon..."

  return (
    <>
      <h1 onMouseOver={onMouseOver} data-value={name} className="text-[8rem] uppercase font-bold hover:italic hover:bg-neutral-100 hover:text-neutral-900 hover:rounded-xl hover:px-4 glitch max-sm:text-5xl max-md:text-7xl max-xmd:text-7xl max-xxs:text-4xl max-xxxs:text-xl">{name}</h1>
      <p className="text-[3rem] uppercase py-4 mt-6 glitch italic max-sm:text-[2rem] max-md-[3rem] max-xxxs:text-lg">
        <span aria-hidden="true">{msg}</span>
          {msg}
        <span aria-hidden="true">{msg}</span>
      </p>
    </>
  );
}



export default Home;